//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class QKEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(QKEvent), typeof(System.Object));
		L.RegFunction("AddCallback", AddCallback);
		L.RegFunction("RemoveCallback", RemoveCallback);
		L.RegFunction("Call", Call);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("New", _CreateQKEvent);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("HasCallback", get_HasCallback, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateQKEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				QKEvent obj = new QKEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: QKEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddCallback(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				QKEvent obj = (QKEvent)ToLua.CheckObject<QKEvent>(L, 1);
				IEventCallback arg0 = (IEventCallback)ToLua.CheckObject<IEventCallback>(L, 2);
				obj.AddCallback(arg0);
				return 0;
			}
			else if (count == 3)
			{
				QKEvent obj = (QKEvent)ToLua.CheckObject<QKEvent>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				LuaEventCallback o = obj.AddCallback(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: QKEvent.AddCallback");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveCallback(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<LuaEventCallback>(L, 2))
			{
				QKEvent obj = (QKEvent)ToLua.CheckObject<QKEvent>(L, 1);
				LuaEventCallback arg0 = (LuaEventCallback)ToLua.ToObject(L, 2);
				obj.RemoveCallback(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<IEventCallback>(L, 2))
			{
				QKEvent obj = (QKEvent)ToLua.CheckObject<QKEvent>(L, 1);
				IEventCallback arg0 = (IEventCallback)ToLua.ToObject(L, 2);
				obj.RemoveCallback(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: QKEvent.RemoveCallback");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Call(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<object[]>(L, 2))
			{
				QKEvent obj = (QKEvent)ToLua.CheckObject<QKEvent>(L, 1);
				object[] arg0 = ToLua.ToObjectArray(L, 2);
				obj.Call(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<object>(L, 2))
			{
				QKEvent obj = (QKEvent)ToLua.CheckObject<QKEvent>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				obj.Call(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: QKEvent.Call");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			QKEvent obj = (QKEvent)ToLua.CheckObject<QKEvent>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasCallback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			QKEvent obj = (QKEvent)o;
			bool ret = obj.HasCallback;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasCallback on a nil value");
		}
	}
}

